# Generated by Django 3.1.2 on 2021-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='description...', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='title', help_text='title', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text='firstname', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(help_text='lastname', max_length=200),
        ),
    ]
